# Generated by Django 3.2 on 2023-03-20 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='ingredient',
        ),
    ]
