# Generated by Django 3.2 on 2023-03-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restor', '0002_remove_food_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='ingredient',
            field=models.ManyToManyField(related_name='ingredients', through='restor.Order', to='restor.Ingredient'),
        ),
    ]
