# Generated by Django 3.2 on 2023-03-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restor', '0003_food_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='food',
            field=models.ManyToManyField(related_name='foods', through='restor.Order', to='restor.Food'),
        ),
    ]
